# Generated by Django 3.2.5 on 2021-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField(blank=True, null=True)),
                ("y", models.IntegerField(blank=True, null=True)),
                ("t", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
