# Generated by Django 3.2.5 on 2021-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='t',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
