# Generated by Django 3.2.5 on 2021-07-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
