# Generated by Django 3.2.5 on 2021-07-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_node_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
