# Generated by Django 3.2.5 on 2021-07-11 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0009_alter_node_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='busobj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canvas.busobj'),
        ),
    ]
