# Generated by Django 3.2.5 on 2021-07-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0010_process_busobj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="process",
            name="busobj",
        ),
        migrations.AddField(
            model_name="process",
            name="busobj",
            field=models.ManyToManyField(blank=True, null=True, to="canvas.BusObj"),
        ),
    ]
