# Generated by Django 3.2.5 on 2021-07-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0011_auto_20210711_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='busobj',
            field=models.ManyToManyField(blank=True, to='canvas.BusObj'),
        ),
    ]
