# Generated by Django 3.2.5 on 2021-07-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0012_alter_process_busobj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="process",
            name="parent",
        ),
        migrations.AddField(
            model_name="process",
            name="parent",
            field=models.ManyToManyField(
                blank=True, related_name="_canvas_process_parent_+", to="canvas.Process"
            ),
        ),
    ]
