# Generated by Django 3.2.5 on 2021-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0016_auto_20210711_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="parent",
            field=models.ManyToManyField(blank=True, to="canvas.Node"),
        ),
    ]
