# Generated by Django 3.2.5 on 2021-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0017_alter_node_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='level',
            field=models.IntegerField(blank=True, choices=[(4, 4), (5, 5), (6, 6)], null=True),
        ),
    ]
