# Generated by Django 3.2.5 on 2021-07-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0019_busobj_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('people', 'people'), ('busobj', 'busobj'), ('obligation', 'obligation'), ('process', 'process'), ('risk', 'risk'), ('metric', 'metric'), ('control', 'control'), ('issue', 'issue')], max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('visible', models.BooleanField()),
                ('incumbant', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_i', models.CharField(blank=True, max_length=255, null=True)),
                ('likelihood_i', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_r', models.CharField(blank=True, max_length=255, null=True)),
                ('likelihood_r', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_category', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('links', models.ManyToManyField(blank=True, related_name='_canvas_db_links_+', to='canvas.Db')),
            ],
        ),
    ]
