# Generated by Django 3.2.5 on 2021-07-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0020_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='visible',
            field=models.BooleanField(null=True),
        ),
    ]
