# Generated by Django 3.2.5 on 2021-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0022_auto_20210712_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='files/')),
                ('type', models.CharField(blank=True, choices=[('people', 'people'), ('busobj', 'busobj'), ('obligation', 'obligation'), ('process', 'process'), ('risk', 'risk'), ('metric', 'metric'), ('control', 'control'), ('issue', 'issue')], max_length=100, null=True)),
            ],
        ),
    ]
