# Generated by Django 3.2.5 on 2021-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0023_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='visible',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='db',
            name='type',
            field=models.CharField(blank=True, choices=[('role', 'role'), ('busobj', 'busobj'), ('obligation', 'obligation'), ('process', 'process'), ('risk', 'risk'), ('metric', 'metric'), ('control', 'control'), ('issue', 'issue')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, choices=[('role', 'role'), ('busobj', 'busobj'), ('obligation', 'obligation'), ('process', 'process'), ('risk', 'risk'), ('metric', 'metric'), ('control', 'control'), ('issue', 'issue')], max_length=100, null=True),
        ),
    ]
