# Generated by Django 3.2.5 on 2021-07-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0024_auto_20210713_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='busobj',
        ),
        migrations.RemoveField(
            model_name='process',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='busobj',
        ),
        migrations.RemoveField(
            model_name='node',
            name='process',
        ),
        migrations.DeleteModel(
            name='BusObj',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
