# Generated by Django 3.2.5 on 2021-07-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0026_auto_20210717_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='date_first',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='db',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Once', 'Once'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=255, null=True),
        ),
    ]
