# Generated by Django 3.2.5 on 2021-07-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0028_auto_20210717_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Failure', 'Failure'), ('Qualified', 'Qualified'), ('Success', 'Success')], max_length=255, null=True),
        ),
    ]
