# Generated by Django 3.2.5 on 2021-07-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0030_auto_20210717_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='frequency_perform',
            field=models.CharField(blank=True, choices=[('Once', 'Once'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='db',
            name='frequency_test',
            field=models.CharField(blank=True, choices=[('Once', 'Once'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=255, null=True),
        ),
    ]
