# Generated by Django 3.2.5 on 2021-07-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0031_auto_20210717_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db',
            old_name='frequency_perform',
            new_name='frequency_inst',
        ),
    ]
